
package helloworld;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.5.2
 * 2012-02-24T15:24:15.858+01:00
 * Generated source version: 2.5.2
 */

@WebFault(name = "faultDetail", targetNamespace = "http://apache.org/hello_world_soap12_http/types")
public class PingMeFault extends Exception {
    
    private helloworld.FaultDetail faultDetail;

    public PingMeFault() {
        super();
    }
    
    public PingMeFault(String message) {
        super(message);
    }
    
    public PingMeFault(String message, Throwable cause) {
        super(message, cause);
    }

    public PingMeFault(String message, helloworld.FaultDetail faultDetail) {
        super(message);
        this.faultDetail = faultDetail;
    }

    public PingMeFault(String message, helloworld.FaultDetail faultDetail, Throwable cause) {
        super(message, cause);
        this.faultDetail = faultDetail;
    }

    public helloworld.FaultDetail getFaultInfo() {
        return this.faultDetail;
    }
}
