package helloworld;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.*;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2012-02-24T15:24:15.944+01:00
 * Generated source version: 2.5.2
 * 
 */
@WebServiceClient(name = "SOAPService", 
                  wsdlLocation = "file:/Users/dehayol/Documents/My Projects/HelloWorld/wsdl/helloworld.wsdl",
                  targetNamespace = "http://apache.org/hello_world_soap12_http")
@BindingType(value=javax.xml.ws.soap.SOAPBinding.SOAP12HTTP_BINDING)
public class SOAPService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://apache.org/hello_world_soap12_http", "SOAPService");
    public final static QName SoapPort = new QName("http://apache.org/hello_world_soap12_http", "SoapPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/Users/dehayol/Documents/My Projects/HelloWorld/wsdl/helloworld.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SOAPService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/Users/dehayol/Documents/My Projects/HelloWorld/wsdl/helloworld.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SOAPService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SOAPService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SOAPService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns Greeter
     */
    @WebEndpoint(name = "SoapPort")
    public Greeter getSoapPort() {
        return super.getPort(SoapPort, Greeter.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Greeter
     */
    @WebEndpoint(name = "SoapPort")
    public Greeter getSoapPort(WebServiceFeature... features) {
        return super.getPort(SoapPort, Greeter.class, features);
    }

}
